tasks:
  - before: if [ ! -f .env ]; then cp .env.example .env; fi

  - name: bash
    command: bash

  - name: flask
    init: cd backend && poetry install
    command: poetry run flask run --debug --host=0.0.0.0

  - name: nextjs
    init: yarn install
    command: yarn dev

ports:
  - port: 3000
    name: nextjs
    onOpen: open-preview

  - port: 5000
    name: flask
    onOpen: ignore
