init: |
  # Copy .env.example to .env if not exists
  if [ ! -f .env ]; then cp .env.example .env; fi
  pip install -r requirements.txt
  npm install

tasks:
  - command: flask run --debug
  - command: npm run dev

ports:
  - port: 5000
    onOpen: open-preview
  - port: 3000
    onOpen: open-preview
