

tasks:

  - before: if [ ! -f .env ]; then cp .env.example .env; fi

  - name: bash
    command: bash

  - name: flask
    init: pip install -r backend/requirements.txt 
    command: flask run --debug

  - name: nextjs
    init: npm install 
    command: npm run dev

ports:

  - port: 3000
    name: nextjs
    onOpen: open-preview

  - port: 5000
    name: flask
    onOpen: ignore