version: "3.9"

services:
  db:
    image: postgres:15
    container_name: needs_assessment_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: needs_assessment
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: needs_assessment_app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/needs_assessment
    depends_on:
      - db
    command: npm run dev  # You can change to 'npm run build && npm start' for production

volumes:
  postgres_data:
