name: API Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      FLASK_API_URL: http://localhost:5000
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: your_secret_here

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Python dependencies with Poetry
        working-directory: backend
        run: poetry install --no-interaction --no-root

      - name: Install Node.js dependencies
        run: yarn install

      - name: Run full test suite (Vitest, Pytest, Next build)
        run: |
          yarn vitest run
          cd backend && poetry run pytest
          yarn build
